### ISSUE TITLE
Is there [Short-chunk CNN + Res] pretrained weight about MTAT dataset?

### ISSUE THREAD

**Issue by rlgnswk** [minzwon/sota-music-tagging-models#10]
Thanks to your great work! Is there [Short-chunk CNN + Res] pretrained weight?

I want to run it, because it is one of outperformed models in MTAT dataset.

but i can not find pretrained weight about MTAT dataset.

**Comment by minzwon** [comment]
Hi rlgnswk,

I don't know why we missed the Short-chunk ResNet but unfortunately, I don't have access to my computer in my university for now. As far as I remember, `models/best_model.pth` is a pretrained Short-chunk CNN (without residual connections) and it shows comparable results. Please try that one!

**Comment by rlgnswk** [comment]
Thanks you! Have a great day!

**Comment by rlgnswk** [comment]
I did, thanks a lot!!



2021년 10월 15일 (금) 오후 10:07, Minz Won ***@***.***>님이 작성:
