### ISSUE TITLE
the difference between musicnn and music600

### ISSUE THREAD

**Issue by Usernamezhx** [minzwon/sota-music-tagging-models#11]
thanks for your work. it's very cool. I want to known  the difference between musicnn and music600. thanks in advance.

**Comment by minzwon** [comment]
Hi,

Unfortunately, I don't exactly remember this. @andrebola do you remember what it was?

**Comment by andrebola** [comment]
Hi! musicnn600 was trained with 600 epochs and all the other models with max 200.

**Comment by minzwon** [comment]
I close this issue as Andres has already answered the question and there was no further question in the last 2 months.
