### ISSUE TITLE
the small data size training.

### ISSUE THREAD

**Issue by Usernamezhx** [minzwon/sota-music-tagging-models#12]
Thanks for your work. I trained the musicnn as your suggestion because I only have 1K train data. I finetune the musicnn last ten layer with the pretrained model you provided which is trained with MSD dataset. the result show me that:
<img width="718" alt="屏幕快照 2021-11-02 下午4 33 14" src="https://user-images.githubusercontent.com/14010625/139812337-4701cd4b-fd89-4d1f-a6db-aac886a21560.png">
<img width="703" alt="屏幕快照 2021-11-02 下午4 33 18" src="https://user-images.githubusercontent.com/14010625/139812363-f7a51129-0d11-457f-9605-02e899c037fe.png">
Does that look right ? thanks in advace.

**Comment by minzwon** [comment]
It looks like your model is overfitted to your training data. I recommend you to fine-tune only the last 1~2 dense layers and also try strong data augmentation for your inputs. You can find a useful data augmentation tool here.

https://github.com/Spijkervet/torchaudio-augmentations.git

**Comment by Usernamezhx** [comment]
> It looks like your model is overfitted to your training data. I recommend you to fine-tune only the last 1~2 dense layers and also try strong data augmentation for your inputs. You can find a useful data augmentation tool here.
> 
> https://github.com/Spijkervet/torchaudio-augmentations.git

thanks for your reply. I will try it.

**Comment by Usernamezhx** [comment]
**I only try last dense layer.maybe it works. but the pr and roc is low than the model trained all layer.**
<img width="796" alt="屏幕快照 2021-11-03 下午4 48 15" src="https://user-images.githubusercontent.com/14010625/140031350-8f38ff79-a271-48d3-bbe3-5b81f62e391f.png">
