### ISSUE TITLE
Do you have the best_model.pth of HarmonicCNN model in MTG data

### ISSUE THREAD

**Issue by sicilyliulc** [minzwon/sota-music-tagging-models#2]
the best_model.pth of HarmonicCNN does not exist, can you sent one?

**Comment by minzwon** [comment]
Hi @sicilyliulc
I don't know why it was missed but we don't have the pretrained HarmonicCNN right now. 
@andrebola will train it again and update as soon as the training is done :)

**Comment by andrebola** [comment]
Hi @sicilyliulc, I added the trained HarmonicCNN to the repository, you can find them under the folder hcnn.
