### ISSUE TITLE
How to get the audio files of MSD?

### ISSUE THREAD

**Issue by millerchx** [minzwon/sota-music-tagging-models#7]
I tried to find a way to download audio files of MSD on millionsongdataset.com but failed. How do I get the audio files of MSD, if I may ask?

**Comment by minzwon** [comment]
Preview audio files used to be available on 7Digital. But for now, there's no way to collect them. I recommend using other public datasets such as MagnaTagATune and MTG-Jamendo.

**Comment by millerchx** [comment]
Thank you. I'll try MTG-Jamendo first.
